### ISSUE TITLE
Cards disappear if game input is wrong

### ISSUE THREAD

**Issue by trinarybits** [trinarybits/trixtak#6]
Observation:
If the index in the test game is not numeric, the last card of the selected card set "disappears" (at least in the console visualization)

Reproduce:
npm run game
Command: h0
Command: hx
Command: tx

Result: the last card of the unused card set is missing, and the hand and trick are empty
Expected result: no card missing, hand contains 1 card, trick contains 0 cards

**Comment by neo-gravity-pawn** [comment]
Expected result is achieved with commit a515f81
